language: csharp
mono: none
dotnet: 5.0.200
solution: WebAppDemo.sln
script:
  - dotnet restore
  - dotnet test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main